---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars:
    controller_validate_certs: "{{ controller_validate_certs }}"
    controller_hostname: 'aap24.beaverdam.com:8443'
  tasks:
    - name: Include vars from configs directory
      ansible.builtin.include_vars:
        dir: "vars/"
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]
      tags:
        - always

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: dispatch
